CREATE TABLE IF NOT EXISTS people
(
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS branch
(
    id SERIAL PRIMARY KEY,
    parent_id INTEGER NOT NULL,
    child_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tree
(
    id SERIAL PRIMARY KEY,
    root_person_id INTEGER NOT NULL
);